services:
  chroma:
    image: chromadb/chroma:0.6.2
    # image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data
    restart: unless-stopped

volumes:
  chroma_data:
